# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:${IMAGE_TAG}
    depends_on:
      - next-js
    build:
      context: ./nginx
      dockerfile: Dockerfile
  mongo:
    image: mongo:${IMAGE_TAG}
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  mongo-express:
    image: mongo-express:${IMAGE_TAG}
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
  next-js:
    image: next-js:${IMAGE_TAG}
    ports:
     - 3000:3000
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    depends_on:
      - mongo-express
      - mongo
    build:
      context: .
      dockerfile: Dockerfile

